
spring:
  application.name: singularity-demo-stream-processing
  cloud:
    stream:
      bindings:
        input.destination: user-topic-transform-data
        output.destination: user-topic-final-data
  kafka:
    client-id: demo-stream-processing
    bootstrap-servers: 35.244.121.169:9092
    template:
      default-topic: user-topic-transform-data
